export interface TextActivityConfig {
  id: string;
  title: string;
  missionNumber: number;
  tagline: string;             // Short, punchy one-liner for the card
  goalStatement: string;       // "In this mission, you will teach the machine to..."
  whyItMatters: string;        // Real-world relevance, 1–2 sentences
  modelName: string;           // e.g., "Naive Bayes Classifier"
  modelAnalogy: string;        // Simple analogy for 7th-graders
  modelIcon: string;           // Material Symbol name
  classA: {
    id: string;
    label: string;
    icon: string;
    colorVar: string; // e.g., var(--color-safe)
    presetMessages: string[];
  };
  classB: {
    id: string;
    label: string;
    icon: string;
    colorVar: string;
    presetMessages: string[];
  };
  trickChallengeDescription: string;
  testSuggestions: string[];
}

export const REAL_VS_SUSPICIOUS_CONFIG: TextActivityConfig = {
  id: 'real-vs-suspicious',
  title: 'Real vs Suspicious',
  missionNumber: 1,
  tagline: 'Can you teach a computer to spot a scam?',
  goalStatement: 'You will teach the machine to tell apart normal, everyday messages from suspicious, scammy ones — just like a spam filter.',
  whyItMatters: 'Every email app in the world uses a version of this. Gmail, Outlook, and iMessage all run classifiers like this one to protect you from phishing and fraud.',
  modelName: 'Naïve Bayes Classifier',
  modelAnalogy: 'Think of the computer as a detective that reads every word you gave it and counts how often each word shows up in "Real" vs "Suspicious" messages. It then uses that count to make a probability guess.',
  modelIcon: 'manage_search',
  classA: {
    id: 'real',
    label: 'Real',
    icon: 'verified',
    colorVar: 'var(--color-safe)',
    presetMessages: [
      'Hey, are we still on for lunch?',
      'Your package has been delivered.',
      'Did you finish the homework?',
      'Happy birthday! Have a great day.',
      'Can you send me the notes from yesterday?'
    ]
  },
  classB: {
    id: 'suspicious',
    label: 'Suspicious',
    icon: 'gpp_bad',
    colorVar: 'var(--color-danger)',
    presetMessages: [
      'URGENT: Your account will be locked!',
      'You won a free iPhone! Click here.',
      'Send $500 to this account immediately.',
      'Update your password NOW.',
      'Click here to claim your prize.'
    ]
  },
  trickChallengeDescription: 'Write a message that you know is Suspicious, but try to trick the model into classifying it as Real!',
  testSuggestions: [
    'Are we going today?',
    'YOUR ACCOUNT IS LOCKED',
    'Hey mom, call me back',
    'Free money click here'
  ]
};

export const HUMAN_VS_ROBOT_CONFIG: TextActivityConfig = {
  id: 'human-vs-robot',
  title: 'Human vs Robot',
  missionNumber: 2,
  tagline: 'Does the machine know who\'s really typing?',
  goalStatement: 'You will teach the machine to detect whether a message sounds like it was written by a human or generated by a robot.',
  whyItMatters: 'Detecting AI-generated text is one of the hottest problems in computer science today. Schools, newsrooms, and social networks all need tools like this.',
  modelName: 'Naïve Bayes Classifier',
  modelAnalogy: 'The computer scores messages based on vocabulary patterns — humans tend to use slang, typos, and emotion words, while robots use formal, mechanical language.',
  modelIcon: 'manage_search',
  classA: {
    id: 'human',
    label: 'Human',
    icon: 'face',
    colorVar: 'var(--color-primary)',
    presetMessages: [
      'Hey! How\'s it going?',
      'I\'m super tired today lol',
      'that movie was okay, not great',
      'brb gotta eat dinner',
      'wow I completely forgot about that'
    ]
  },
  classB: {
    id: 'robot',
    label: 'Robot',
    icon: 'smart_toy',
    colorVar: 'var(--color-warning)',
    presetMessages: [
      'Error code 404: Emotion not found.',
      'Processing request. Please wait.',
      'Beep boop. I am a machine.',
      'System update required.',
      'Affirmative. Task completed.'
    ]
  },
  trickChallengeDescription: 'Write a mathematically precise sentence but try to trick the model into thinking you are Human!',
  testSuggestions: [
    'Initiating sleep sequence.',
    'I love pizza so much',
    'What\'s up dude',
    'Data processing complete.'
  ]
};

export const FIX_THE_MODEL_CONFIG: TextActivityConfig = {
  id: 'fix-the-model',
  title: 'Fix the Model',
  missionNumber: 4,
  tagline: 'What happens when the training data is bad?',
  goalStatement: 'You will discover why bad training data breaks a working model — then fix it yourself and retrain.',
  whyItMatters: 'In the real world, most AI failures are caused by bad data, not bad math. The model is only as smart as the examples it learns from.',
  modelName: 'Naïve Bayes Classifier',
  modelAnalogy: 'If you teach a kid that triangles are circles by showing them bad examples, they will get it wrong every time. The same is true for machines — garbage in, garbage out.',
  modelIcon: 'manage_search',
  classA: {
    id: 'school',
    label: 'School',
    icon: 'school',
    colorVar: 'var(--color-primary)',
    presetMessages: [
      'Don\'t forget about the science project!',
      'What page was the reading tonight?',
      'Can I borrow a pencil tomorrow?'
    ]
  },
  classB: {
    id: 'weekend',
    label: 'Weekend',
    icon: 'celebration',
    colorVar: 'var(--color-accent)',
    presetMessages: [
      'Want to come over and play games?',
      'Let\'s go to the park on Saturday.',
      // The intentionally bad data:
      'Math test on Friday don\'t forget to study',
      'Homework is due on Monday morning'
    ]
  },
  trickChallengeDescription: 'Notice anything weird? Test the word "Math test" and see what happens. Then go delete the bad data and fix the model!',
  testSuggestions: [
    'Are we doing homework?',
    'Saturday is going to be fun',
    'Math test'
  ]
};
